Des 185 dashborad page
generaciondesafiante/Regresemos_a_casa_UI pull request #3
Opened 2023-10-11 14:42 UTC by Daniielmayo

creation and completion of the page dashboard

2023-10-11 15:58 UTC, abdulflorez approved these changes

2023-10-11 16:57 UTC, DanielCalleCO commented on components/organisms/Login/Login.tsx
> +// import { useAuthStore } from ".././../../hooks";
if you don't need this, delete it.

2023-10-11 16:58 UTC, DanielCalleCO commented on components/organisms/Login/Login.tsx
> +// interface LoginFormFields {
delete or add an additional comment to explain why is there..

2023-10-11 16:58 UTC, DanielCalleCO commented on components/organisms/Login/Login.tsx
> +  // const {
remove

2023-10-11 16:58 UTC, DanielCalleCO commented on components/organisms/Login/Login.tsx
> +  // const {
remove

2023-10-11 16:58 UTC, DanielCalleCO commented on hooks/useAuthStore.ts
> +// export interface AuthStore {
remove

2023-10-11 16:59 UTC, DanielCalleCO commented on middlewares/middlewareAuh.ts
> +  console.log(sesionAuth);
remove this clg and the next comment... or add a comment explaining.

2023-10-11 16:59 UTC, DanielCalleCO commented on store/auth/authSlice.tsx
> +// Define el tipo para el estado inicial
translation

2023-10-11 16:59 UTC, DanielCalleCO commented on store/auth/authSlice.tsx
> +// Define el tipo para las acciones
translation

2023-10-11 17:54 UTC, DanielCalleCO requested changes

2023-10-11 17:54 UTC, DanielCalleCO commented on components/organisms/DashboardUserWelcome/DashboardUserWelcome..tsx
> +        {/* <h2 className={styles["continue-course_subtitle"]}>¡Recursos para ti!</h2> */}
do we need this?

2023-10-11 21:14 UTC, DanielCalleCO commented on components/organisms/DashboardUserWelcome/DashboardUserWelcome..tsx
> +        {/* <h2 className={styles["continue-course_subtitle"]}>¡Recursos para ti!</h2> */}
once you solve this, re-request my review please

2023-10-12 13:26 UTC, DanielCalleCO requested changes

2023-10-12 13:26 UTC, DanielCalleCO commented on hooks/useAuthStore.ts
> +  user: Partial<UserData>; // Permite propiedades opcionales en user
translate

2023-10-12 13:26 UTC, DanielCalleCO commented on hooks/useAuthStore.ts
> +      console.log("autenticado");
remove

2023-10-12 15:14 UTC, DanielCalleCO approved these changes

2023-10-12 15:20 UTC, merged